version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ordering
    ports:
      - "5432:5432"
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr 127.0.0.1:9092
    ports:
      - "9092:9092"
