name: CI/CD Pipeline - Takealot Ordering Microservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TakealotOrderingMicroservice.sln

      - name: Build solution
        run: dotnet build --no-restore -c Release TakealotOrderingMicroservice.sln

      - name: Run unit tests
        run: |
          if [ -d "Ordering.Application.Tests" ]; then
            echo "Running unit tests..."
            dotnet test Ordering.Application.Tests/Ordering.Application.Tests.csproj --no-build -c Release --verbosity normal
          else
            echo " No test project found skipping tests."
          fi

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/takealot-ordering-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/takealot-ordering-api:v1.${{ github.run_number }}

      - name: Post-build summary
        run: |
          echo "Docker image pushed successfully!"
          echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/takealot-ordering-api:v1.${{ github.run_number }}"
