name: Build and Test Takealot Ordering Microservice

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TakealotOrdering.sln

      - name: Build solution
        run: dotnet build --no-restore -c Release

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal --configuration Release



